leaderboard tot format bug
    `elif` was missing, which meant that
    when format was set to "tot", it would execute that branch, then look to match more formats, and fail

      File "/home/dietz/auto-judge-code-test/trec_auto_judge/judge_runner.py", line 313, in _write_leaderboard
        leaderboard.write(leaderboard_path)
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
      File "/home/dietz/auto-judge-code-test/trec_auto_judge/leaderboard/leaderboard.py", line 77, in write
        raise ValueError(f"Unknown format: {format!r}")
    ValueError: Unknown format: 'tot'